### ISSUE TITLE
Invalid URL with # char

### ISSUE THREAD

**Issue by highchoice** [Cybersecurity-Ethical-Hacker/xssuccessor#1]
python3 xssuccessor.py -d "http://testhtml5.vulnweb.com/#/redir?url=gggg" 
...
Please provide a URL with at least one query parameter (e.g., https://example.com/page?param1=value&param2=test)                                                  

❌ Error: Invalid URL format.
🧩 URL must include at least one query parameter.

The encoded # doesn't work too.
python3 xssuccessor.py -d "http://testhtml5.vulnweb.com/%23/redir?url=gggg"

**Comment by Cybersecurity-Ethical-Hacker** [comment]
I apply a patch for it.

Please update the tool using:

`python xssuccessor.py -u`

and check again.

Thanks for the report.

**Comment by highchoice** [comment]
URLs are parsed correctly now. 
But the tool doesn't detect DOM-based XSS at this time, right?
I mean, "url" param is vulnerable  "http://testhtml5.vulnweb.com/#/redir?url=javascript:alert(1)" but not detected.

**Comment by Cybersecurity-Ethical-Hacker** [comment]
Yes for the moment is only for XSS Reflected as it was developed most to check the validity of the results.

Next step is the DOM based.

**Comment by Cybersecurity-Ethical-Hacker** [comment]
DOM Based support added !

Please use: 
`python xssuccessor.py -u`
