### ISSUE TITLE
Permission issue 

### ISSUE THREAD

**Issue by bugsrootx0** [Cybersecurity-Ethical-Hacker/xssuccessor#3]
![ee](https://github.com/user-attachments/assets/e2a22ecd-2041-403b-aba2-f5849e0144b2)
![ss](https://github.com/user-attachments/assets/7e94d4c4-654e-4b28-a0a2-471264b7630b)

**Comment by bugsrootx0** [comment]
I also installed PlayWright, but no module named 'PlayWright' message showed 
"Traceback (most recent call last):
  File "/home/mrlazybugs/Downloads/xssuccessor/xssuccessor.py", line 29, in <module>
    from playwright.async_api import async_playwright, Browser, BrowserContext, Page
ModuleNotFoundError: No module named 'playwright'
"
after installing the PlayWright module in super user (root) mood. 
and when this tool opens a normal user, then it works but is not scanning any domain. when i scan a domain  like "python xssuccessor.py -d https://www.taratrans.me/?page," then this message is shown: "Error: [Errno 13] Permission denied: 'scans'
ERROR:root:Unhandled exception: [Error 13] Permission denied:'scans''
Traceback (most recent call last):
  File "/usr/lib/python3.12/pathlib.py", line 1313, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'scans/www.taratrans.me'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrlazybugs/Downloads/xssuccessor/xssuccessor.py", line 1611, in async_main
    config = Config(args, playwright_version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrlazybugs/Downloads/xssuccessor/xssuccessor.py", line 796, in __init__
    self._setup_directories(args)
  File "/home/mrlazybugs/Downloads/xssuccessor/xssuccessor.py", line 841, in _setup_directories
    self.base_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.12/pathlib.py", line 1317, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.12/pathlib.py", line 1313, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied:'scans''
"

**Comment by Cybersecurity-Ethical-Hacker** [comment]
As i mention in the Readme file you should not install Playwright in Kali Linux. It is already installed. 

You just need to to use git clone and run it. Dependencies also included in Kali Linux.

sudo also is not needed.

Please check again the documentation.

**Comment by bugsrootx0** [comment]
its work . thank you boss
